apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acegrocer.fullname" . }}
  labels:
    {{- include "acegrocer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "acegrocer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "acegrocer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acegrocer.serviceAccountName" . }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: COOKIE_NAME
              value: {{ .Values.env.COOKIE_NAME | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- $defaultSecretName := printf "%s-secrets" (include "acegrocer.fullname" .) -}}
                  name: {{ default $defaultSecretName .Values.secret.name }}
                  key: JWT_SECRET
            - name: COOKIE_SAMESITE
              value: {{ .Values.env.COOKIE_SAMESITE | quote }}
            - name: COOKIE_SECURE
              value: {{ .Values.env.COOKIE_SECURE | quote }}
            - name: RATE_LIMIT_ENABLED
              value: {{ .Values.env.RATE_LIMIT_ENABLED | quote }}
            - name: RATE_LIMIT_WINDOW_MS
              value: {{ .Values.env.RATE_LIMIT_WINDOW_MS | quote }}
            - name: RATE_LIMIT_MAX
              value: {{ .Values.env.RATE_LIMIT_MAX | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ default $defaultSecretName .Values.secret.name }}
                  key: DATABASE_URL
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /app/prisma
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "acegrocer.fullname" . }}-pvc
      {{- end }}
