import { test, expect } from '@playwright/test'

// Use pre-authenticated admin storage state generated by setup project
test.use({ storageState: 'playwright/.auth/admin.json' })

test('PATCH /api/admin/orders returns 400 for invalid payload', async ({ page }) => {

  const resp = await page.request.patch('/api/admin/orders', {
    data: { id: -1, status: 'INVALID' },
  })
  expect(resp.status()).toBe(400)
  const json = await resp.json()
  expect(json?.error).toBeTruthy()
})

test('PATCH /api/admin/orders returns 404 for non-existent order', async ({ page }) => {

  const resp = await page.request.patch('/api/admin/orders', {
    data: { id: 999999, status: 'SHIPPED' },
  })
  expect(resp.status()).toBe(404)
  const json = await resp.json()
  expect(json?.error).toBeTruthy()
})
