image:
  repository: ghcr.io/OWNER/REPO/acegrocer # TODO: set to your GHCR image path
  tag: latest # or use a specific tag/sha in CD

replicaCount: 1

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ace-next.kunlecreates.org
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-storage

env:
  NODE_ENV: production
  PORT: "3000"
  COOKIE_NAME: acegrocer_auth
  COOKIE_SAMESITE: Lax
  COOKIE_SECURE: "true"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "120"
  # DATABASE_URL provided via Helm Secret from values; path is inside container
  DATABASE_URL: file:./prisma/dev.db

secret:
  create: false
  name: "" # defaulted to <release>-secrets by chart
