# Default values for acegrocer.
# These are intended for production; override in your environment-specific values files.

image:
  repository: ghcr.io/OWNER/REPO/acegrocer
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  # Application env variables
  NODE_ENV: production
  PORT: "3000"
  # JWT cookie and security settings
  COOKIE_NAME: acegrocer_auth
  JWT_SECRET: CHANGEME
  COOKIE_SAMESITE: Lax
  COOKIE_SECURE: "true"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "120"
  # Database connection (SQLite for single-pod scenarios; prefer Postgres for multi-replica)
  DATABASE_URL: file:./prisma/dev.db

# Secret management: by default, expect secret to be created externally (e.g., by CD)
secret:
  create: false
  name: "" # defaults to "<release>-secrets" when empty

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podLabels: {}

nodeSelector: {}

affinity: {}

tolerations: []

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: acegrocer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
